### ISSUE TITLE
Controller.get_all_nodes_conn_status fails when zero nodes are connected.

### ISSUE THREAD

**Issue by jonstout** [BRCDcomm/pybvc#1]
[Problem area](https://github.com/BRCDcomm/pybvc/blob/master/pybvc/controller/controller.py#L393)

```
elif (resp.status_code == 200):
            p1 = 'nodes'
            p2 = 'node'
            if(p1 in resp.content and p2 in resp.content):
                status.set_status(STATUS.OK)
                itemlist = json.loads(resp.content).get(p1).get(p2)
                for item in itemlist:
```

As far as I can tell `resp.content` is just the body of the html response (a string) which means any response that contains "nodes" will also contain "node" ("node" is a substring of "nodes"); This makes the second half of the if statement on line 396 meaningless. The function `json.loads(resp.content).get(p1).get(p2)` then silently fails and returns `None` when the key "node" is absent (zero nodes are connected). The iteration over `itemlist` on line 399 then fails.

```
Traceback (most recent call last):
  File "poll.py", line 37, in <module>
    res = ctrl.get_all_nodes_conn_status()
  File "/usr/local/lib/python2.7/dist-packages/pybvc-1.1.1-py2.7.egg/pybvc/controller/controller.py", line 399, in get_all_nodes_conn_status
    for item in itemlist:
TypeError: 'NoneType' object is not iterable
```

**Comment by s-garbuzov** [comment]
Agreed. Will fix it. Thanks for the pointing on it.

**Comment by jebpublic** [comment]
Fixed.
