### ISSUE TITLE
Create NOS Driver for VDX

### ISSUE THREAD

**Issue by gaberger** [BRCDcomm/pybvc#4]
This feature request is to add a driver for VDX

**Comment by jebpublic** [comment]
Great feature request!  We definitely want to increase the number of NETCONF devices supported beyond our current vRouter.  Hope someone from community can take a look at vRouter implementation and create one for VDX.  If not we will add it to the core team's roadmap.  If you are interested in taking this issue let us know by placing a comment here (and we don't have duplicated effort).  At this time, the core team is not working on this.  If this changes we will add a comment here.

**Comment by gaberger** [comment]
I am working on it.. This is to prepare for the PR
